export const postings = {
  FETCH_PENDING: 'FETCH_POSTINGS_PENDING',
  FETCH_SUCCESS: 'FETCH_POSTINGS_SUCCESS',
  FETCH_ERROR: 'FETCH_POSTINGS_ERROR',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
};

export const user = {};
